// CREATE TABLE refresh_token(
// id SERIAL PRIMARY KEY,
//   user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
//   token_hash VARCHAR(64) NOT NULL,
// created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
// expires_at TIMESTAMP NOT NULL

// )
